title: Service
content:
  - subtitle: "Research Community:"
  - body: I am a member of the editorial board for ACM Transactions on Computer-Human-Interaction (ToCHI) and ACM Transactions on Accessible Computing (TACCESS). I recently served as the Technical Program Co-Chair for ACM <a href="url">CHI 2020</a> and the Program Chair for ACM <a href="url">ASSETS 2018</a>.<br><br>

  - subtitle: "Department of Computer Science and UBC:"
  - body: I am serving on the Dean’s Advisory Committee on Promotion and Tenures (DACOPAT) and CS’s Peer Teaching Evaluation. I have recently served as the Chair for CS’s inaugural Committee on Outreach Diversity and Equity (CODE) and as the Associate Head of CS’s Graduate Program.
hyper_name: "READ MORE"
hyper_path: "/assets/images/CV_McGrenere.pdf"
caption: Presenting the best student paper award at ASSETS 2018
para: "Full details can be found on page 15 of my "
